### ISSUE TITLE
Caught exception from lodeloader - java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by Tsyklop** [marcin212/LodeLoader#3]
crash: http://pastebin.com/4uWPsMga (error from log file)

crash report: http://pastebin.com/F6sZUAVR

ImmersiveEngineering-0.6.4 immersiveintegration-0.6.5

**Comment by marcin212** [comment]
Not updated to v0.6 yet. I'm thinking if I should, since Immersive Engineering added minetweaker functionality.

https://github.com/BluSunrize/ImmersiveEngineering/blob/master/src/main/java/blusunrize/immersiveengineering/common/util/compat/minetweaker/Excavator.java
